### PR TITLE
feat: add handler for application keys endpoint

### PR DESCRIPTION
**Pull request by mateuszkulpa**
# Scope of changes
- Added a handler for fetching application keys from the `/admin/api/accounts/%d/applications/%d/keys.json` endpoint.

### CODE REVIEW

**Comment by eguzki** [comment]
Good contribution, LGTM. 

Can you add methods to delete keys and create a new key? Should not be hard.

**Comment by mateuszkulpa** [comment]
> Good contribution, LGTM.
> 
> Can you add methods to delete keys and create a new key? Should not be hard.

@eguzki 
I'd like to implement it, but to be honest I'm not sure how to extract the key after creation.
Here is an example request:

```
curl --location --request POST 'http://master-account.3scale.localhost:3000/admin/api/accounts/18/applications/84/keys.json' \
--header 'accept: */*' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'access_token=YOUR_ACCESS_TOKEN'
```

If we don't pass any key - so it's generated on the server, but we don't get the generated key in the body. We just get a link to all the keys.

```
{
    "application": {
        "id": 84,
        "state": "live",
        "enabled": true,
        "created_at": "2024-02-08T10:15:11Z",
        "updated_at": "2024-02-08T10:15:11Z",
        "service_id": 1,
        "service_name": "Master Service",
        "plan_id": 13,
        "plan_name": "test plan",
        "account_id": 18,
        "org_name": "TEST ORG",
        "first_traffic_at": null,
        "first_daily_traffic_at": null,
        "application_id": "e6082a1b",
        "links": [
            {
                "rel": "self",
                "href": "http://master-account.3scale.localhost/admin/api/accounts/18/applications/84"
            },
            {
                "rel": "service",
                "href": "http://master-account.3scale.localhost/admin/api/services/1"
            },
            {
                "rel": "account",
                "href": "http://master-account.3scale.localhost/admin/api/accounts/18"
            },
            {
                "rel": "plan",
                "href": "http://master-account.3scale.localhost/admin/api/services/1/application_plans/13"
            },
            {
                "rel": "keys",
                "href": "http://master-account.3scale.localhost/admin/api/accounts/18/applications/84/keys"
            },
            {
                "rel": "referrer_filters",
                "href": "http://master-account.3scale.localhost/admin/api/accounts/18/applications/84/referrer_filters"
            }
        ],
        "name": "test 2",
        "description": "test 2"
    }
}
```

**Comment by eguzki** [comment]
> application_id

Application keys are available from a different 3scale API endpoint

Screenshot 2024-02-08 at 13-37-31 3scale API Documentation Red Hat 3scale API Management


Use JSON endpoints, try to avoid xml endpoints

**Comment by mateuszkulpa** [comment]
@eguzki 
That's clear. I tried using json endpoint to create application key.

```
curl --location --request POST 'http://master-account.3scale.localhost:3000/admin/api/accounts/18/applications/84/keys.json' \
--header 'accept: */*' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'access_token=YOUR_ACCESS_TOKEN'
```

The problem here is that the endpoint returns an application object instead of a generated key.
We could call another endpoint (GET all keys) after generating a new key, but then we can't be sure which key is new.

**Comment by eguzki** [comment]
> @eguzki That's clear. I tried using json endpoint to create application key.
> 
> ```
> curl --location --request POST 'http://master-account.3scale.localhost:3000/admin/api/accounts/18/applications/84/keys.json' \
> --header 'accept: */*' \
> --header 'Content-Type: application/x-www-form-urlencoded' \
> --data-urlencode 'access_token=YOUR_ACCESS_TOKEN'
> ```
> 
> The problem here is that the endpoint returns an application object instead of a generated key. We could call another endpoint (GET all keys) after generating a new key, but then we can't be sure which key is new.

Indeed, the create keys endpoint returns the application entity instead of the newly created key. Not very appropriate, but still good enough. 

Note that the create key endpoint accepts passing a custom key or generate a random one for you. 

I came up with the implementation when testing :yum: 

```diff
diff --git a/client/app.go b/client/app.go
index 07863ab..c4c5f47 100644
--- a/client/app.go
+++ b/client/app.go
@@ -2,6 +2,7 @@ package client
 
 import (
        "fmt"
+       "io"
        "net/http"
        "net/url"
        "strconv"
@@ -249,6 +250,44 @@ func (c *ThreeScaleClient) ApplicationKeys(accountId, id int64) ([]ApplicationKe
        return keys, nil
 }
 
+func (c *ThreeScaleClient) CreateApplicationRandomKey(accountId, id int64) (Application, error) {
+       return c.createApplicationKey(accountId, id, nil)
+}
+
+func (c *ThreeScaleClient) CreateApplicationKey(accountId, id int64, key string) (Application, error) {
+       return c.createApplicationKey(accountId, id, &key)
+}
+
+func (c *ThreeScaleClient) createApplicationKey(accountId, id int64, key *string) (Application, error) {
+       var app Application
+       endpoint := fmt.Sprintf(appKeys, accountId, id)
+
+       var body io.Reader
+       if key != nil {
+               values := url.Values{}
+               values.Add("key", *key)
+               body = strings.NewReader(values.Encode())
+       }
+
+       req, err := c.buildPostReq(endpoint, body)
+       if err != nil {
+               return app, httpReqError
+       }
+
+       resp, err := c.httpClient.Do(req)
+       if err != nil {
+               return app, err
+       }
+       defer resp.Body.Close()
+
+       apiResp := &ApplicationElem{}
+       err = handleJsonResp(resp, http.StatusCreated, apiResp)
+       if err != nil {
+               return app, err
+       }
+       return apiResp.Application, nil
+}
```

The `3scale-porta-go-client` does not care more than that. It is up the higher level layer using this SDK to decide if they want random generated ones or with an specific name.

**Comment by mateuszkulpa** [comment]
@eguzki Thanks for your suggestions ❤️  I've added create and delete methods.

**Review by eguzki — APPROVED** [review]

**Comment by eguzki** [comment]
@mateuszkulpa good job! 

You are done with PR? I can merge if so.

**Comment by mateuszkulpa** [comment]
> @mateuszkulpa good job!
> 
> You are done with PR? I can merge if so.

Thanks! You can merge it 😄

**Pull request merged**
