### PR TITLE
account proxy endpoint

### PR DESCRIPTION
**Pull request by eguzki**
Implement new endpoint `GET /admin/api/account/proxy_configs/%s.json`.

Added pagination params `page`, `per_page`

### Verification steps

* Create > 500 products in one tenant. Promote the product configuration to staging or production. 
* Run `ListAccountProxyConfigs` method and verify all the proxy_configs (1 per product) are in the response. It should be >500. `account_proxy_config_latest_read.go` file
```go
func main() {                                                                                   
    var (                                                                                       
        env     string  = "sandbox"                                                          
        version *string = &[]string{"latest"}[0]                                                
        host *string                                                                            
    )                                                                                           
                                                      
    c := helper.Generic_client()      //     client.NewThreeScale(adminPortal, accessToken)                                                
    obj, err := c.ListAccountProxyConfigs(env, version, host)                                   
    if err != nil {                                                                             
        panic(err)                                                                              
    }                                                                                           
                                                                                                
    helper.PrintJson(obj)                                                                       
}                                                                                               

```

```
$ go run account_proxy_config_latest_read.go | jq '.proxy_configs | length'
550
```

### CODE REVIEW

**Comment by austincunningham** [comment]
Code changes look good . I will verify

**Comment by austincunningham** [comment]
#Verified 
- deployed 3scale via the operator
- wrote a go program to hit the endpoint
```go
    host:="api-3scale-apicast-production.apps.aucunnin.6ltc.s1.devshift.org"
    version:= "1"
    proxyConfigList, err := threescaleClient.ListAccountProxyConfigs("sandbox",&version,&host)
    if err != nil {
		fmt.Printf("%+v\n", err)
		return
	}
	jsonPrint(proxyConfigList)
```

```bash
go run main.go
```
output as follows

```json
{
  "proxy_configs": [
    {
      "proxy_config": {
        "id": 1,
        "version": 1,
        "environment": "sandbox",
        "content": {
          "id": 2,
          "account_id": 2,
          "name": "API",
          "oneline_description": null,
          "description": null,
          "txt_api": null,
          "txt_support": null,
          "txt_features": null,
          "created_at": "2023-02-22T10:06:29Z",
          "updated_at": "2023-02-22T10:08:19Z",
          "logo_file_name": null,
          "logo_content_type": null,
          "logo_file_size": null,
          "state": "incomplete",
          "intentions_required": false,
          "draft_name": "",
          "infobar": null,
          "terms": null,
          "display_provider_keys": false,
          "tech_support_email": null,
          "admin_support_email": null,
          "credit_card_support_email": null,
          "buyers_manage_apps": true,
          "buyers_manage_keys": true,
          "custom_keys_enabled": true,
          "buyer_plan_change_permission": "request",
          "buyer_can_select_plan": false,
          "notification_settings": null,
          "default_application_plan_id": 7,
          "default_service_plan_id": 5,
          "default_end_user_plan_id": null,
          "end_user_registration_required": false,
          "tenant_id": 2,
          "system_name": "api",
          "backend_version": "1",
          "mandatory_app_key": true,
          "buyer_key_regenerate_enabled": true,
          "support_email": "admin@3scale.apps.aucunnin.6ltc.s1.devshift.org",
          "referrer_filters_required": false,
          "deployment_option": "hosted",
          "proxiable?": true,
          "backend_authentication_type": "service_token",
          "backend_authentication_value": "211c2158a292e12a6197aed02b04afcb487d53bb4d3baa99e09dd6988afbfda0",
          "proxy": {
            "id": 2,
            "tenant_id": 2,
            "service_id": 2,
            "endpoint": "https://api-3scale-apicast-production.apps.aucunnin.6ltc.s1.devshift.org:443",
            "deployed_at": null,
            "api_backend": "https://echo-api.3scale.net:443",
            "auth_app_key": "app_key",
            "auth_app_id": "app_id",
            "auth_user_key": "user_key",
            "credentials_location": "query",
            "error_auth_failed": "Authentication failed",
            "error_auth_missing": "Authentication parameters missing",
            "created_at": "2023-02-22T10:06:29Z",
            "updated_at": "2023-02-22T10:08:19Z",
            "error_status_auth_failed": 403,
            "error_headers_auth_failed": "text/plain; charset=us-ascii",
            "error_status_auth_missing": 403,
            "error_headers_auth_missing": "text/plain; charset=us-ascii",
            "error_no_match": "No Mapping Rule matched",
            "error_status_no_match": 404,
            "error_headers_no_match": "text/plain; charset=us-ascii",
            "secret_token": "Shared_secret_sent_from_proxy_to_API_backend_986ba36c4a263307",
            "hostname_rewrite": null,
            "oauth_login_url": null,
            "sandbox_endpoint": "https://api-3scale-apicast-staging.apps.aucunnin.6ltc.s1.devshift.org:443",
            "api_test_path": "/",
            "api_test_success": null,
            "apicast_configuration_driven": true,
            "oidc_issuer_endpoint": null,
            "lock_version": 1,
            "authentication_method": "1",
            "hostname_rewrite_for_sandbox": "echo-api.3scale.net",
            "endpoint_port": 443,
            "valid?": true,
            "service_backend_version": "1",
            "hosts": [
              "api-3scale-apicast-production.apps.aucunnin.6ltc.s1.devshift.org",
              "api-3scale-apicast-staging.apps.aucunnin.6ltc.s1.devshift.org"
            ],
            "backend": {
              "endpoint": "https://backend-3scale.apps.aucunnin.6ltc.s1.devshift.org",
              "host": "backend-3scale.apps.aucunnin.6ltc.s1.devshift.org"
            },
            "policy_chain": [
              {
                "name": "apicast",
                "version": "builtin",
                "configuration": {}
              }
            ],
            "proxy_rules": [
              {
                "id": 2,
                "proxy_id": 2,
                "http_method": "GET",
                "pattern": "/",
                "metric_id": 6,
                "metric_system_name": "hits",
                "delta": 1,
                "tenant_id": 2,
                "created_at": "2023-02-22T10:06:29Z",
                "updated_at": "2023-02-22T10:06:29Z",
                "redirect_url": null,
                "parameters": [],
                "querystring_parameters": {},
                "position": 1
              }
            ]
          }
        }
      }
    }
  ]
}
```
Sent the same request via the api docs
```bash
curl -v  -X GET "https://3scale-admin.apps.aucunnin.6ltc.s1.devshift.org/admin/api/account/proxy_configs/sandbox.json?access_token=<Tokenhere>&host=api-3scale-apicast-production.apps.aucunnin.6ltc.s1.devshift.org&version=1"
```
compared the json output to porta.client
```json
{
 "proxy_configs": [
  {
   "proxy_config": {
    "id": 1,
    "version": 1,
    "environment": "sandbox",
    "content": {
     "id": 2,
     "account_id": 2,
     "name": "API",
     "description": null,
     "txt_support": null,
     "created_at": "2023-02-22T10:06:29Z",
     "updated_at": "2023-02-22T10:08:19Z",
     "logo_file_name": null,
     "logo_content_type": null,
     "logo_file_size": null,
     "state": "incomplete",
     "intentions_required": false,
     "terms": null,
     "buyers_manage_apps": true,
     "buyers_manage_keys": true,
     "custom_keys_enabled": true,
     "buyer_plan_change_permission": "request",
     "buyer_can_select_plan": false,
     "notification_settings": null,
     "default_application_plan_id": 7,
     "default_service_plan_id": 5,
     "tenant_id": 2,
     "system_name": "api",
     "backend_version": "1",
     "mandatory_app_key": true,
     "buyer_key_regenerate_enabled": true,
     "support_email": "admin@3scale.apps.aucunnin.6ltc.s1.devshift.org",
     "referrer_filters_required": false,
     "deployment_option": "hosted",
     "kubernetes_service_link": null,
     "proxiable?": true,
     "backend_authentication_type": "service_token",
     "backend_authentication_value": "211c2158a292e12a6197aed02b04afcb487d53bb4d3baa99e09dd6988afbfda0",
     "proxy": {
      "service_id": 2,
      "api_test_path": "/",
      "id": 2,
      "secret_token": "Shared_secret_sent_from_proxy_to_API_backend_986ba36c4a263307",
      "sandbox_endpoint": "https://api-3scale-apicast-staging.apps.aucunnin.6ltc.s1.devshift.org:443",
      "endpoint": "https://api-3scale-apicast-production.apps.aucunnin.6ltc.s1.devshift.org:443",
      "error_status_no_match": 404,
      "error_status_auth_missing": 403,
      "error_status_auth_failed": 403,
      "error_status_limits_exceeded": 429,
      "hostname_rewrite": null,
      "oauth_login_url": null,
      "credentials_location": "query",
      "auth_app_id": "app_id",
      "auth_app_key": "app_key",
      "auth_user_key": "user_key",
      "error_headers_auth_failed": "text/plain; charset=us-ascii",
      "error_headers_auth_missing": "text/plain; charset=us-ascii",
      "error_headers_no_match": "text/plain; charset=us-ascii",
      "error_auth_failed": "Authentication failed",
      "error_auth_missing": "Authentication parameters missing",
      "error_no_match": "No Mapping Rule matched",
      "error_headers_limits_exceeded": "text/plain; charset=us-ascii",
      "error_limits_exceeded": "Usage limit exceeded",
      "oidc_issuer_endpoint": null,
      "oidc_issuer_type": "keycloak",
      "authentication_method": "1",
      "staging_domain": "api-3scale-apicast-staging.apps.aucunnin.6ltc.s1.devshift.org",
      "production_domain": "api-3scale-apicast-production.apps.aucunnin.6ltc.s1.devshift.org",
      "apicast_configuration_driven": true,
      "tenant_id": 2,
      "deployed_at": null,
      "created_at": "2023-02-22T10:06:29Z",
      "updated_at": "2023-02-22T10:08:19Z",
      "api_test_success": null,
      "lock_version": 1,
      "hostname_rewrite_for_sandbox": "echo-api.3scale.net",
      "endpoint_port": 443,
      "api_backend": "https://echo-api.3scale.net:443",
      "valid?": true,
      "service_backend_version": "1",
      "hosts": [
       "api-3scale-apicast-production.apps.aucunnin.6ltc.s1.devshift.org",
       "api-3scale-apicast-staging.apps.aucunnin.6ltc.s1.devshift.org"
      ],
      "backend": {
       "endpoint": "https://backend-3scale.apps.aucunnin.6ltc.s1.devshift.org",
       "host": "backend-3scale.apps.aucunnin.6ltc.s1.devshift.org"
      },
      "policy_chain": [
       {
        "name": "apicast",
        "version": "builtin",
        "configuration": {}
       }
      ],
      "jwt_claim_with_client_id": null,
      "jwt_claim_with_client_id_type": null,
      "proxy_rules": [
       {
        "id": 2,
        "proxy_id": 2,
        "http_method": "GET",
        "pattern": "/",
        "metric_id": 6,
        "metric_system_name": "hits",
        "delta": 1,
        "tenant_id": 2,
        "created_at": "2023-02-22T10:06:29Z",
        "updated_at": "2023-02-22T10:06:29Z",
        "redirect_url": null,
        "position": 1,
        "last": false,
        "owner_id": 2,
        "owner_type": "Proxy",
        "parameters": [],
        "querystring_parameters": {}
       }
      ]
     }
    }
   }
  }
 ]
}```

@eguzki hmm seems to return the same proxyconfiglist ,I expected them to be the same but there are some differences 
![proxyconfigList](https://user-images.githubusercontent.com/16667688/220610587-b8fb06ef-7e17-4450-b697-0aeff7c2abc5.gif) 
I don't think this is enough to block merging this ? What do you think ?

**Comment by eguzki** [comment]
Super nice verification @austincunningham ! I feel shame for not doing that in the first place!

Regarding the differences, after reviewing, I would say most (if not all of them) are marshal/unmarshal differences. Your are comparing object raw response with Marshal(Unmarsha(raw response)). BTW, I think it is interesting exercise to detect unimplemented fields

**Comment by eguzki** [comment]
I will keep this PR open. I want to add pagination params

**Comment by eguzki** [comment]
ready for review @austincunningham

**Review by austincunningham — APPROVED** [review]

**Pull request merged**
