### PR TITLE
Create tenants and activate pending users

### PR DESCRIPTION
**Pull request by eguzki**
- [x] Create Tenants
- [x] Activate ``pending` user

### CODE REVIEW

**Comment by eguzki** [comment]
`json` much better than `xml`. We should use `json`. 

Besides, 3scale API is deprecating xml format. Some new endpoints available for the coming release will be available only in `json` format.

**Comment by PhilipGough** [comment]
@eguzki Yep agree. Well if you want to refactor this PR to use son then be my guest, that would be great👍 

However if you need to get this merged to do what you're doing, go for it, and we can make the refactor a bigger task at some point.

**Comment by eguzki** [comment]
let me do this in another PR

**Comment by eguzki** [comment]
rebased to new master for CircleCi check

**Pull request merged**
